/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fish.client.view;

import fish.client.FishSettings;
import fish.client.controller.ClientController;
import java.io.File;
import java.io.IOException;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * The gui frame to edit the preferences
 * @author alfredo
 */
public class PreferencesFrame extends javax.swing.JFrame {

    private ClientController client;
    private Preferences prefs;
    /**
     * Creates new form PreferencesFrame
     * @param c  the client controller
     */
    public PreferencesFrame(ClientController c) {
        initComponents();
        client = c;
        this.FolderLabel.setText(c.getSettings().getFolder());
        this.DestinationFolderLabel.setText(c.getSettings().getDownloadFolder().toString());
        this.ServerListFileLabel.setText(c.getSettings().getServerListFilePath());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        intervalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FolderLabel = new javax.swing.JLabel();
        ChangeFolderButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DestinationFolderLabel = new javax.swing.JLabel();
        ChangeDestinationFolderButton = new javax.swing.JButton();
        ServerListFileButton = new javax.swing.JButton();
        ServerListFileLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setText("Statistics refresh time (ms)");

        intervalTextField.setText("5000");

        jLabel2.setText("Folder to share");

        ChangeFolderButton.setText("Change Folder");
        ChangeFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeFolderButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Server File List");

        jLabel6.setText("Destination Folder");

        DestinationFolderLabel.setText("--------------------");

        ChangeDestinationFolderButton.setText("Change Destination");
        ChangeDestinationFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeDestinationFolderButtonActionPerformed(evt);
            }
        });

        ServerListFileButton.setText("File");
        ServerListFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerListFileButtonActionPerformed(evt);
            }
        });

        ServerListFileLabel.setText("--------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(156, Short.MAX_VALUE)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ServerListFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ServerListFileButton)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ChangeDestinationFolderButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DestinationFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(60, 60, 60)
                                        .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ChangeFolderButton))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(intervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangeFolderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ChangeDestinationFolderButton)
                            .addComponent(DestinationFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ServerListFileButton)
                    .addComponent(ServerListFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * close without saving
     * @param evt 
     */
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed

        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    /**
     * closes and saves the new preferences
     * @param evt 
     */
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        try {
            client.getSettings().setRefreshInterval(intervalTextField.getText());
            client.getSettings().setFolder(this.FolderLabel.getText());
            client.getSettings().setDownloadFolder(this.DestinationFolderLabel.getText());
            client.getSettings().setServerListFile(ServerListFileLabel.getText());
            client.restartDownloadFolderWatcher();
            client.refreshListOfServersFromFile();
            
            prefs = Preferences.userNodeForPackage(fish.client.view.FishMainFrame.class);
            prefs.put(FishSettings.SHARED_FOLDER, this.FolderLabel.getText());
            prefs.put(FishSettings.DOWNLOAD_FOLDER, this.DestinationFolderLabel.getText());
            prefs.put(FishSettings.SERVER_FOLDER, ServerListFileLabel.getText());

            this.dispose();
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_SaveButtonActionPerformed

    
    /**
     * shows the selection for the folder to share
     * @param evt 
     */
    private void ChangeFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeFolderButtonActionPerformed
        // TODO add your handling code here:
        prefs = Preferences.userNodeForPackage(fish.client.view.FishMainFrame.class);
        final JFileChooser fc = new JFileChooser(prefs.get(FishSettings.SHARED_FOLDER, ""));

        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            FolderLabel.setText(file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }

    }//GEN-LAST:event_ChangeFolderButtonActionPerformed

    
    /**
     * shows the selection for the folder to download to
     * @param evt 
     */
    private void ChangeDestinationFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeDestinationFolderButtonActionPerformed

        prefs = Preferences.userNodeForPackage(fish.client.view.FishMainFrame.class);
        final JFileChooser fc = new JFileChooser(prefs.get(FishSettings.DOWNLOAD_FOLDER, ""));

        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            DestinationFolderLabel.setText(file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_ChangeDestinationFolderButtonActionPerformed

    
    /**
     * shows the selection for the file containing the list of servers
     * @param evt 
     */
    private void ServerListFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerListFileButtonActionPerformed
        // TODO add your handling code here:

        prefs = Preferences.userNodeForPackage(fish.client.view.FishMainFrame.class);
        final JFileChooser fc = new JFileChooser(prefs.get(FishSettings.SERVER_FOLDER, ""));

        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            ServerListFileLabel.setText(file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }

    }//GEN-LAST:event_ServerListFileButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ChangeDestinationFolderButton;
    private javax.swing.JButton ChangeFolderButton;
    private javax.swing.JLabel DestinationFolderLabel;
    private javax.swing.JLabel FolderLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton ServerListFileButton;
    private javax.swing.JLabel ServerListFileLabel;
    private javax.swing.JTextField intervalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
